import type { Metadata } from "next";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { cn } from "@/utils";
import { ViewTransitions } from "next-view-transitions";
import Providers from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn("antialiased bg-brand-white")}>
          <Providers>{children}</Providers>
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              style: {
                background: "var(--color-stone-100)",
                color: "var(--color-stone-95  0)",
                border: "1px solid var(--color-stone-300)",
              },
            }}
          />
        </body>
      </html>
    </ViewTransitions>
  );
}
